# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_HTK', [dirname(__file__)])
        except ImportError:
            import _HTK
            return _HTK
        if fp is not None:
            try:
                _mod = imp.load_module('_HTK', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _HTK = swig_import_helper()
    del swig_import_helper
else:
    import _HTK
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x



def SetPath(*args):
  return _HTK.SetPath(*args)
SetPath = _HTK.SetPath
class Callback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Callback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Callback, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _HTK.delete_Callback
    __del__ = lambda self : None;
    def run(self, *args): return _HTK.Callback_run(self, *args)
    def __init__(self): 
        if self.__class__ == Callback:
            _self = None
        else:
            _self = self
        this = _HTK.new_Callback(_self, )
        try: self.this.append(this)
        except: self.this = this
    def __disown__(self):
        self.this.disown()
        _HTK.disown_Callback(self)
        return weakref_proxy(self)
Callback_swigregister = _HTK.Callback_swigregister
Callback_swigregister(Callback)

class Caller(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Caller, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Caller, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _HTK.new_Caller()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _HTK.delete_Caller
    __del__ = lambda self : None;
    def start(self): return _HTK.Caller_start(self)
    def stop_pause(self): return _HTK.Caller_stop_pause(self)
    def delCallback(self): return _HTK.Caller_delCallback(self)
    def setCallback(self, *args): return _HTK.Caller_setCallback(self, *args)
    def call(self, *args): return _HTK.Caller_call(self, *args)
Caller_swigregister = _HTK.Caller_swigregister
Caller_swigregister(Caller)



