# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LsplParser', [dirname(__file__)])
        except ImportError:
            import _LsplParser
            return _LsplParser
        if fp is not None:
            try:
                _mod = imp.load_module('_LsplParser', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LsplParser = swig_import_helper()
    del swig_import_helper
else:
    import _LsplParser
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LsplParser.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _LsplParser.SwigPyIterator_value(self)
    def incr(self, n = 1): return _LsplParser.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _LsplParser.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _LsplParser.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _LsplParser.SwigPyIterator_equal(self, *args)
    def copy(self): return _LsplParser.SwigPyIterator_copy(self)
    def next(self): return _LsplParser.SwigPyIterator_next(self)
    def __next__(self): return _LsplParser.SwigPyIterator___next__(self)
    def previous(self): return _LsplParser.SwigPyIterator_previous(self)
    def advance(self, *args): return _LsplParser.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _LsplParser.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _LsplParser.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _LsplParser.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _LsplParser.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _LsplParser.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _LsplParser.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _LsplParser.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _LsplParser.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _LsplParser.StringVector___nonzero__(self)
    def __bool__(self): return _LsplParser.StringVector___bool__(self)
    def __len__(self): return _LsplParser.StringVector___len__(self)
    def pop(self): return _LsplParser.StringVector_pop(self)
    def __getslice__(self, *args): return _LsplParser.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _LsplParser.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _LsplParser.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _LsplParser.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _LsplParser.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _LsplParser.StringVector___setitem__(self, *args)
    def append(self, *args): return _LsplParser.StringVector_append(self, *args)
    def empty(self): return _LsplParser.StringVector_empty(self)
    def size(self): return _LsplParser.StringVector_size(self)
    def clear(self): return _LsplParser.StringVector_clear(self)
    def swap(self, *args): return _LsplParser.StringVector_swap(self, *args)
    def get_allocator(self): return _LsplParser.StringVector_get_allocator(self)
    def begin(self): return _LsplParser.StringVector_begin(self)
    def end(self): return _LsplParser.StringVector_end(self)
    def rbegin(self): return _LsplParser.StringVector_rbegin(self)
    def rend(self): return _LsplParser.StringVector_rend(self)
    def pop_back(self): return _LsplParser.StringVector_pop_back(self)
    def erase(self, *args): return _LsplParser.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _LsplParser.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _LsplParser.StringVector_push_back(self, *args)
    def front(self): return _LsplParser.StringVector_front(self)
    def back(self): return _LsplParser.StringVector_back(self)
    def assign(self, *args): return _LsplParser.StringVector_assign(self, *args)
    def resize(self, *args): return _LsplParser.StringVector_resize(self, *args)
    def insert(self, *args): return _LsplParser.StringVector_insert(self, *args)
    def reserve(self, *args): return _LsplParser.StringVector_reserve(self, *args)
    def capacity(self): return _LsplParser.StringVector_capacity(self)
    __swig_destroy__ = _LsplParser.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _LsplParser.StringVector_swigregister
StringVector_swigregister(StringVector)


def setRMLpath(*args):
  return _LsplParser.setRMLpath(*args)
setRMLpath = _LsplParser.setRMLpath
class LsplParser(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LsplParser, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LsplParser, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _LsplParser.new_LsplParser()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LsplParser.delete_LsplParser
    __del__ = lambda self : None;
    def loadMorphology(self): return _LsplParser.LsplParser_loadMorphology(self)
    def createNewNamespace(self): return _LsplParser.LsplParser_createNewNamespace(self)
    def eraseNamespace(self, *args): return _LsplParser.LsplParser_eraseNamespace(self, *args)
    def addPatternToNamespace(self, *args): return _LsplParser.LsplParser_addPatternToNamespace(self, *args)
    def parseTextInNamespace(self, *args): return _LsplParser.LsplParser_parseTextInNamespace(self, *args)
LsplParser_swigregister = _LsplParser.LsplParser_swigregister
LsplParser_swigregister(LsplParser)

class MatchResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MatchResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MatchResult, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _LsplParser.new_MatchResult(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LsplParser.delete_MatchResult
    __del__ = lambda self : None;
    def getQuestionVariants(self): return _LsplParser.MatchResult_getQuestionVariants(self)
    def getObjectsVariants(self): return _LsplParser.MatchResult_getObjectsVariants(self)
MatchResult_swigregister = _LsplParser.MatchResult_swigregister
MatchResult_swigregister(MatchResult)



